[package]
name = "reserve-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
reserve-horizon.workspace = true
reserve-signer.workspace = true
stellar-xdr.workspace = true
stellar-strkey.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
sha2.workspace = true
hmac.workspace = true
base64.workspace = true
hex.workspace = true

[dev-dependencies]
tokio = { workspace = true }
